### ISSUE TITLE
Implementation of `$ safe auth` command

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-cli#7]
Includes client auth to send auth request and receive auth credentials, store and read them. Create internal API to read them and to be used by all commands to connect.

**Comment by calumcraig** [comment]
Tested against the above referenced PR #29 

Now, in order to access the (mock) network, the `safe_cli` app needs to be authorised by the `safe-authenticator-cli` app.

Asking for authorisation:
![Screenshot from 2019-06-14 16-47-29](https://user-images.githubusercontent.com/44327924/59521706-d7658680-8ec4-11e9-98b3-150aedc45494.png)

App is authorised and connected to the (mock) network:
![Screenshot from 2019-06-14 16-48-22](https://user-images.githubusercontent.com/44327924/59521724-e4827580-8ec4-11e9-993a-c1c923af7093.png)

**Comment by calumcraig** [comment]
Moving this to done.
